name: playful-programming-cms

services:
  pgsql:
    image: postgres:16.10-alpine3.22
    env_file:
      - .env
    volumes:
      - pgsql_storage:/var/lib/postgresql/data
      - pgsql_backups:/backups
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    image: redis:8.2.1-alpine3.22
    volumes:
      - redis_storage:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  rustfs:
    image: rustfs/rustfs
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web UI Port
    volumes:
      - rustfs_storage:/data
    environment:
      RUSTFS_ACCESS_KEY: ${S3_KEY_ID}
      RUSTFS_SECRET_KEY: ${S3_KEY_SECRET}
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-ec",
          "curl \"http://127.0.0.1:9000/health\" && \
          curl \"http://127.0.0.1:9001/rustfs/console/health\""
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    environment:
      S3_ENDPOINT: http://rustfs:9000
      POSTGRES_URL: postgresql://postgres:unicorn@pgsql:5432/postgres
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on: [pgsql, redis, rustfs]
    profiles: [app]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:3000 && wget --no-verbose --tries=1 --spider http://0.0.0.0:3001 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - path: .
          action: rebuild
    post_start:
      - command: node --experimental-strip-types packages/db/scripts/migrate.ts

volumes:
  pgsql_storage: {}
  pgsql_backups: {}
  redis_storage: {}
  rustfs_storage: {}
