name: playful-programming-hoof

services:
  pgsql:
    image: postgres:16.10-alpine3.22
    env_file:
      - .env
    volumes:
      - pgsql_storage:/var/lib/postgresql/data
      - pgsql_backups:/backups
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    image: redis:8.2.1-alpine3.22
    volumes:
      - redis_storage:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  rustfs:
    image: rustfs/rustfs
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web UI Port
    volumes:
      - rustfs_storage:/data
    environment:
      RUSTFS_ACCESS_KEY: ${S3_KEY_ID}
      RUSTFS_SECRET_KEY: ${S3_KEY_SECRET}
    healthcheck:
      test: [
          "CMD",
          "sh",
          "-ec",
          "curl -f \"http://127.0.0.1:9000/health\" && \
          curl -f \"http://127.0.0.1:9001/rustfs/console/health\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: playful-programming-hoof:latest
    environment:
      MOCK_PROXY_PORT: 3999
      IN_DOCKER: true
    profiles: [e2e]
    command: node apps/e2e/mocks/index.ts
    healthcheck:
      test: netstat -tln | grep :3999
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: playful-programming-hoof:latest
    env_file:
      - .env
    environment:
      NODE_USE_ENV_PROXY: 1
      NODE_EXTRA_CA_CERTS: /var/app/apps/e2e/src/generated/cert.pem
      HTTP_PROXY: http://proxy:3999
      HTTPS_PROXY: http://proxy:3999
      NO_PROXY: "localhost, 127.0.0.1"
      S3_ENDPOINT: http://rustfs:9000
      POSTGRES_URL: postgresql://postgres:unicorn@pgsql:5432/postgres
      REDIS_URL: redis://redis:6379
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rustfs:
        condition: service_healthy
      proxy:
        condition: service_healthy
    profiles: [e2e]
    ports:
      - "3333:3000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:3000 && wget --no-verbose --tries=1 --spider http://0.0.0.0:3001 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    post_start:
      - command: node packages/db/scripts/migrate.ts

  e2e:
    image: playful-programming-hoof:latest
    environment:
      API_URL: http://app:3000
      IN_DOCKER: true
    depends_on:
      app:
        condition: service_healthy
    profiles: [e2e]
    command: pnpm -C apps/e2e vitest

volumes:
  pgsql_storage: {}
  pgsql_backups: {}
  redis_storage: {}
  rustfs_storage: {}
