name: playful-programming-hoof

services:
  pgsql:
    image: postgres:16.10-alpine3.22
    env_file:
      - .env
    volumes:
      - pgsql_storage:/var/lib/postgresql/data
      - pgsql_backups:/backups
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 500ms
    networks: [shared]
    ports:
      - "5432:5432"

  redis:
    image: redis:8.2.1-alpine3.22
    volumes:
      - redis_storage:/data
    networks: [shared]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 500ms

  rustfs:
    image: rustfs/rustfs
    networks: [shared]
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web UI Port
    volumes:
      - rustfs_storage:/data
    environment:
      RUSTFS_ACCESS_KEY: ${S3_KEY_ID}
      RUSTFS_SECRET_KEY: ${S3_KEY_SECRET}
    healthcheck:
      test: [
          "CMD",
          "sh",
          "-ec",
          "curl -f \"http://127.0.0.1:9000/health\" && \
          curl -f \"http://127.0.0.1:9001/rustfs/console/health\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 500ms

  proxy:
    build:
      context: .
      target: e2e-proxy
    image: playful-programming-hoof-e2e-proxy:latest
    environment:
      MOCK_PROXY_PORT: 3999
    volumes:
      - ./e2e/mocks/src:/var/app/e2e/mocks/src:ro
    networks: [shared]
    healthcheck:
      test: netstat -tln | grep :3999
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 100ms

volumes:
  pgsql_storage: {}
  pgsql_backups: {}
  redis_storage: {}
  rustfs_storage: {}

networks:
  shared:
    name: hoof_shared_network
