# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
app = 'hoof-api'
primary_region = 'ewr'

[build]

[deploy]
  release_command = "node --experimental-strip-types packages/db/scripts/migrate.ts"

[processes]
  app = "node --experimental-strip-types apps/api/src/index.ts"
  worker = "node --experimental-strip-types apps/worker/src/index.ts"

[env]
  PORT = "8080"
  WORKER_PORT = "8081"
  ENVIRONMENT = "production"
  SITE_URL = "https://playfulprogramming.com"
  S3_PUBLIC_URL = "https://fly.storage.tigris.dev"
  S3_ENDPOINT = "https://fly.storage.tigris.dev"
  S3_BUCKET = "hoof-storage"
  REDIS_URL = "redis://hoof-redis.internal:6379"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

  [[http_service.checks]]
    grace_period = "30s"
    interval = "60s"
    method = "GET"
    timeout = "10s"
    path = "/health/redis"

  [[http_service.checks]]
    grace_period = "30s"
    interval = "60s"
    method = "GET"
    timeout = "10s"
    path = "/health/postgres"

[checks]
  [checks.worker_http]
    type = "http"
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"
    port = 8081
    processes = ['worker']


[[vm]]
  size = "shared-cpu-1x"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['worker']
