packages:
  - apps/**
  - packages/**
onlyBuiltDependencies:
  - esbuild
  - libpq
  - msgpackr-extract
  - msw
  - nx
  - sharp
catalog:
  "@sinclair/typebox": ^0.34.41
  bullmq: ^5.40.2
  drizzle-orm: ^0.44.6
  undici: ^7.18.2
  vitest: ^4.0.16
  ioredis: ^5.8.2
  openapi-fetch: ^0.15.0
  openapi-typescript: ^7.10.1
  sharp: ^0.34.4
  gray-matter: ^4.0.3
  "@types/hast": ^3.0.4
