packages:
  - apps/**
  - packages/**
onlyBuiltDependencies:
  - esbuild
  - libpq
  - msgpackr-extract
  - msw
  - nx
  - sharp
catalog:
  "@sinclair/typebox": ^0.34.41
  "@vitest/coverage-v8": ^4.0.5
  bullmq: ^5.40.2
  drizzle-orm: 1.0.0-beta.15-859cf75
  gray-matter: ^4.0.3
  ioredis: ^5.8.2
  openapi-fetch: ^0.15.0
  openapi-typescript: ^7.10.1
  sharp: ^0.34.4
  undici: ^7.18.2
  vite: ^7.0.0
  vitest: ^4.0.16
  "@types/hast": ^3.0.4
