packages:
  - apps/**
  - packages/**
onlyBuiltDependencies:
  - esbuild
  - libpq
  - msgpackr-extract
  - msw
  - nx
  - sharp
catalog:
  "@sinclair/typebox": ^0.34.33
  bullmq: ^5.40.2
  drizzle-orm: ^0.44.2
