name: Fly Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-group # ensure only one deploy action runs at a time
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      - name: Deploy App
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_DEPLOY_TOKEN }}

  deploy-redis:
    name: Deploy redis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      - name: Deploy Redis
        working-directory: ./services/redis
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_REDIS_DEPLOY_TOKEN }}
